
/* ---------- JavaScript ---------- */
const qaData = {
    aws: {
      EC2:[{q:"1.What is Amazon EC2?",a:"Amazon EC2 (Elastic Compute Cloud) is a web service that provides resizable compute capacity in the cloud. It allows you to launch and manage virtual servers called instances."},
           {q:"2.What is an EC2 stand for?",a:"EC2 stands for Elastic Compute Cloud."},
           {q:"3. What is an EC2 instance?",a:"An EC2 instance is a virtual server in Amazon’s cloud used to run applications."},
           {q:"4. What is an AMI?",a:"An Amazon Machine Image (AMI) is a pre-configured template used to create an EC2 instance. It includes the operating system, software, and configuration settings."},
           {q:"5. What are the different types of EC2 instances?",a:"Common types are: General Purpose (e.g., t2, t3),Compute Optimized (e.g., c5),Memory Optimized (e.g., r5),Storage Optimized (e.g., i3),Accelerated Computing (e.g., p3, g4)."},
           {q:"6. What is an instance type?",a:"Instance type defines the hardware configuration (CPU, memory, storage, network) of an EC2 instance."},
           {q:"7. What is the default storage for EC2?",a:"EBS (Elastic Block Store) is the default persistent storage for EC2 instances."},
           {q:"8. What is EBS?",a:"Amazon Elastic Block Store provides block-level storage volumes for use with EC2 instances."},
           {q:"9. What is the difference between EBS and Instance Store?",a:"EBS: Persistent, data remains after instance termination.Instance Store: Temporary, data is lost when instance stops or terminates."},
           {q:"10. What is a security group?",a:"A Security Group acts as a virtual firewall that controls inbound and outbound traffic to EC2 instances."},
           {q:"11. What is a key pair in EC2?",a:"A key pair (public and private key) is used for secure SSH or RDP access to EC2 instances."},
           {q:"12. What operating systems can we run on EC2?",a:"You can run Linux, Windows, and macOS operating systems."},
           {q:"13. What is Elastic IP?",a:"An Elastic IP is a static IPv4 address that you can assign to your instance for consistent public access."},
           {q:"14. What is user data in EC2?",a:"User Data is a script that runs automatically when an instance is launched, usually used for initial setup or configuration."},
           {q:"15. How do you connect to a Linux EC2 instance?",a:"Using SSH (Secure Shell) and the .pem private key file."},
           {q:"16. What is on-demand instance?",a:"An On-Demand Instance is pay-as-you-go; you pay for compute capacity by the hour or second without long-term commitment."},
           {q:"17. What is a spot instance?",a:"Spot Instances let you use unused EC2 capacity at a lower price, but they can be interrupted when demand increases."},
           {q:"18. What is a reserved instance?",a:"Reserved Instances offer discounted rates if you commit to using EC2 for 1 or 3 years."},
           {q:"19. What is auto scaling?",a:"Auto Scaling automatically increases or decreases the number of instances based on demand."},
           {q:"20. What is a load balancer?",a:"A Load Balancer distributes incoming network traffic across multiple EC2 instances to ensure high availability."},
          
           {q:"INTERMEDIATE LEVEL EC2 INTERVIEW QUESTIONS",a:"INTERMEDIATE LEVEL EC2 INTERVIEW ANSWERS"},

           {q:"1. What is the difference between Stop and Terminate in EC2?",a:"Stop: Shuts down the instance but retains the EBS volume.Terminate: Deletes the instance and associated EBS volumes (unless “Delete on Termination” is disabled)."},
           {q:"2. What are EC2 instance states?",a:"Pending → Running → Stopping → Stopped → Shutting-down → Terminated"},
           {q:"3. What is the root device volume?",a:"The root device volume contains the image used to boot the instance (from AMI)."},
           {q:"4. Can you change the instance type after launching it?",a:"Yes- by stopping the instance, changing the instance type, and restarting it."},
           {q:"5. What is placement group in EC2?",a:"Placement Groups are logical groupings of instances for specific network performance:Cluster: Low latency, high performance.Spread: Instances spread across hardware.Partition: Isolated hardware groups for large workloads."},
           {q:"6. How does EC2 handle high availability?",a:"By launching instances in multiple Availability Zones (AZs) and using Auto Scaling and Load Balancing."},
           {q:"7. What is the difference between public and private IP?",a:"Public IP: Accessible over the internet.Private IP: Used for internal communication within a VPC."},
           {q:"8. What is EC2 metadata?",a:"Metadata provides information about the running instance (e.g., instance ID, IP, region).Access via: http://169.254.169.254/latest/meta-data/"},
           {q:"9. What is EC2 monitoring?",a:"Using Amazon CloudWatch to track instance metrics like CPU usage, network traffic, and disk I/O."},
           {q:"10. What is EC2 Hibernate?",a:"Hibernate saves the instance’s RAM data to disk and resumes faster when restarted, like sleep mode."},
           {q:"11. What are EC2 launch templates?",a:"They define instance configuration (AMI, type, key pair, security groups) to simplify repeatable launches."},
           {q:"12. What is an Elastic Network Interface (ENI)?",a:"An ENI is a virtual network interface that you can attach to an EC2 instance for networking flexibility."},
           {q:"13. What is EC2 instance lifecycle?",a:"The process an instance goes through from creation → running → stopping → termination."},
           {q:"14. Can you attach multiple EBS volumes to one EC2 instance?",a:"Yes, you can attach multiple EBS volumes to a single instance."},
           {q:"15. What is the maximum number of security groups per instance?",a:"You can associate up to 5 security groups per network interface."},
           {q:"16. What is the default limit for EC2 instances per region?",a:"Typically 20 instances per region, but it can be increased by request."},
           {q:"17. What are burstable performance instances?",a:"Instances like t2/t3 that accumulate CPU credits when idle and use them during high performance needs."},
           {q:"18. How do you back up an EC2 instance?",a:"By creating an EBS Snapshot or AMI (machine image)."},
           {q:"19. What happens when an instance is terminated?",a:"The instance stops running, EBS volumes may be deleted, and data on instance store is lost."},
           {q:"20. What is the difference between EC2 and Lambda?",a:"EC2: You manage servers and choose instance types.Lambda: Serverless, AWS manages everything; you just upload code."}],
           


      S3:[{q:"What is Amazon S3?",a:"Amazon S3 (Simple Storage Service) is an object storage service that allows you to store and retrieve data anytime from anywhere on the web."},
          {q:"2. What does S3 stand for?",a:"S3 stands for Simple Storage Service."},
          {q:"3. What is an S3 bucket?",a:"A bucket is a container for storing objects (files) in Amazon S3. It’s like a folder in the cloud."},
          {q:"4. What is in S3 object?",a:"An object is a file and its metadata stored inside an S3 bucket."},
          {q:"5. What is the maximum size of a single S3 object?",a:"Each S3 object can be up to 5 TB in size"},
          {q:"6. What is the maximum number of buckets per AWS account?",a:"You can create up to 100 buckets per AWS account (by default)."},
          {q:"7. How is data stored in S3?",a:"Data is stored as objects within buckets. Each object has a key (name), value (data), and metadata."},
          {q:"8. What is an S3 key?",a:"The key is the unique name that identifies an object within a bucket."},
          {q:"9. What are the different storage classes in S3?",a:"S3 Standard,S3 Intelligent-Tiering,S3 Standard-IA (Infrequent Access),S3 One Zone-IA,S3 Glacier,S3 Glacier Deep Archive"},
          {q:"10. What is S3 Standard?",a:"S3 Standard is the default storage class, used for frequently accessed data with high durability and availability."},
          {q:"11. What is the durability of S3?",a:"S3 provides 99.999999999% (11 nines) durability."},
          {q:"12. What is the availability of S3?",a:"S3 offers 99.99% availability."},
          {q:"13. What is S3 versioning?",a:"Versioning keeps multiple versions of an object in the same bucket, protecting against accidental overwrites or deletions."},
          {q:"14. Can S3 store folders?",a:"Not really — S3 is flat (no folders). “Folders” are simulated using prefixes in object names."},
          {q:"15. How can you upload files to S3?",a:"You can upload files using the AWS Management Console, AWS CLI, or SDKs (like Python Boto3)."},
          {q:"16. What is an S3 URL?",a:"An S3 URL is a unique web address used to access an object, such as:https://bucket-name.s3.amazonaws.com/object-name"},
          {q:"17. What is an S3 bucket policy?",a:"A bucket policy defines who can access your bucket and what actions they can perform."},
          {q:"18. Can you host a static website on S3?",a:"Yes, S3 can host static websites (HTML, CSS, JavaScript)."},
          {q:"19. What is S3 Lifecycle Management?",a:"It automatically moves data between storage classes or deletes old data based on defined rules."},
          {q:"20. What is the difference between S3 and EBS?",a:"S3: Object storage (used for files, backups, static websites).EBS: Block storage (used for EC2 instances, databases)."},

          {q:"INTERMEDIATE LEVEL S3 INTERVIEW QUESTIONS",a:"INTERMEDIATE LEVEL S3 INTERVIEW ANSWERS"},

          {q:"1. What is S3 Intelligent-Tiering?",a:"It automatically moves data between frequent and infrequent access tiers to reduce costs."},
          {q:"2. What is S3 Glacier?",a:"S3 Glacier is a low-cost storage class for archiving data that is rarely accessed. Retrieval time varies from minutes to hours."},
          {q:"3. What is S3 Glacier Deep Archive?",a:"An even cheaper storage option for data that is rarely accessed — ideal for long-term archiving (retrieval time: 12–48 hours)."},
          {q:"4. What is S3 cross-region replication (CRR)?",a:"CRR automatically copies objects across different AWS regions for disaster recovery or compliance."},
          {q:"5. What is S3 same-region replication (SRR)?",a:"SRR replicates data between buckets within the same region, often used for data backup or logging."},
          {q:"6. What is the difference between S3 ACLs and Bucket Policies?",a:"ACLs (Access Control Lists): Control permissions at the object or bucket level.Bucket Policies: JSON-based rules that define access for users or services."},
          {q:"7. What is S3 Transfer Acceleration?",a:"It speeds up file uploads using Amazon CloudFront’s global edge locations."},
          {q:"8. What is S3 Event Notification?",a:"It triggers an event (like SNS, SQS, or Lambda) when an action occurs, e.g., when a new object is uploaded."},
          {q:"9. What are S3 pre-signed URLs?",a:"A pre-signed URL gives temporary access to a private object without making it public."},
          {q:"10. What is the difference between S3 and Glacier?",a:"S3: For frequently accessed data.Glacier: For long-term, rarely accessed data."},
          {q:"11. What is S3 object lock?",a:"It prevents objects from being deleted or modified for a fixed retention period — used for compliance."},
          {q:"12. What is S3 Select?",a:"S3 Select lets you query specific data from objects (like CSV or JSON) using SQL-like queries without downloading the whole file."},
          {q:"13. What is S3 Access Point?",a:"An Access Point provides unique access URLs and permissions for specific applications or users accessing a shared bucket."},
          {q:"14. What is S3 encryption?",a:"Encryption secures your data. Types include:,SSE-S3 (Managed by AWS),SSE-KMS (Managed by KMS),SSE-C (Customer-provided keys),Client-side encryption"},
          {q:"15. What is multipart upload in S3?",a:"For large files, multipart upload splits the file into smaller parts and uploads them in parallel for speed and reliability."},
          {q:"16. What is S3 replication time control (RTC)?",a:"It ensures that objects are replicated to another region within 15 minutes."},
          {q:"17. What is S3 storage class analysis?",a:"It helps you identify data access patterns to optimize lifecycle rules and cost."},
          {q:"18. How can you secure S3 data?",a:"nable encryption,Use IAM policies,Apply bucket policies,Enable MFA delete,Disable public access"},
          {q:"19. What is MFA delete in S3?",a:"It requires multi-factor authentication (MFA) to permanently delete objects or disable versioning — adds extra protection."},
          {q:"20. What monitoring tools are available for S3?",a:"AWS CloudWatch – for metrics and alerts,AWS CloudTrail – for logging API activity,S3 Storage Lens – for usage and cost insights"}],

      IAM:[{q:"1. What is IAM in AWS?",a:"AWS Identity and Access Management (IAM) is a service that helps you securely control who can access AWS resources and what actions they can perform."},
              {q:"2. What does IAM stand for?",a:"IAM stands for Identity and Access Management."},
              {q:"3. Is IAM a global or regional service?",a:"IAM is a global service — it’s not specific to any region."},
              {q:"4. What is an IAM user?",a:"An IAM user is an individual identity created in AWS to represent a person or application that interacts with AWS resources."},
              {q:"5. What is an IAM group?",a:"An IAM group is a collection of IAM users. You can assign permissions to a group instead of each user individually."},
              {q:"6. What is an IAM role?",a:"An IAM role is an identity with permissions that can be assumed by users, applications, or AWS services temporarily."},
              {q:"7. What are IAM policies?",a:"Policies are JSON documents that define permissions — what actions are allowed or denied on specific AWS resources."},
              {q:"8. What is the root user in AWS?",a:"The root user is the account owner (created when you sign up for AWS). It has full access to all AWS services and resources."},
              {q:"9. What is the difference between root user and IAM user?",a:"Root user: Has unrestricted access.IAM user: Has limited access based on assigned policies."},
              {q:"10. What are permissions in IAM?",a:"Permissions define what actions a user or role can perform on AWS resources."},
              {q:"11. What is the default permission for a new IAM user?",a:"By default, new IAM users have no permissions until explicitly granted."},
              {q:"12. What are managed policies?",a:"Managed policies are pre-built permission sets provided by AWS or created by users that can be attached to multiple users, groups, or roles."},
              {q:"13. What are inline policies?",a:"Inline policies are directly embedded within a single user, group, or role — not reusable elsewhere."},
              {q:"14. What is the IAM policy structure?",a:"A policy is a JSON document containing:-Version,Statement,Effect (Allow/Deny),Action,Resource"},
              {q:"15. What is multi-factor authentication (MFA)?",a:"MFA adds an extra layer of security by requiring a password and a temporary verification code (from a device or app)."},
              {q:"16. What is the principle of least privilege?",a:"It means giving users only the permissions they need to perform their tasks — nothing more."},
              {q:"17. How do you access IAM?",a:"Through:,AWS Management Console,AWS CLI,AWS SDKs,IAM API"},
              {q:"18. Can one IAM user have multiple access keys?",a:"Yes — each IAM user can have two active access keys at a time."},
              {q:"19. What are IAM access keys used for?",a:"Access keys (Access Key ID + Secret Key) are used for programmatic access (via CLI, SDKs, or APIs)."},
              {q:"20. What is a password policy in IAM?",a:"It defines rules for password complexity, length, and expiration to enhance account security."},
              
              {q:"INTERMEDIATE LEVEL IAM INTERVIEW QUESTIONS ",a:"INTERMEDIATE LEVEL IAM INTERVIEW ANSWERS"},

              {q:"1. What is the difference between IAM roles and IAM users?",a:"IAM user: Has long-term credentials.IAM role: Used for temporary access and can be assumed by services or users."},
              {q:"2. What is IAM federation?",a:"Federation allows users from an external identity system (like Google, Azure AD, or corporate AD) to access AWS resources without creating separate IAM users."},
              {q:"3. What is an assume role policy?",a:"It defines who (principal) can assume a role and under what conditions."},
              {q:"4. What is an IAM trust policy?",a:"A trust policy specifies which entities (users, services, or accounts) are allowed to assume a role."},
              {q:"5. What is the difference between identity-based and resource-based policies?",a:"Identity-based: Attached to users, groups, or roles.Resource-based:- Attached directly to resources (e.g., S3 bucket policies)."},
              {q:"6. What is a policy simulator in IAM?",a:"Its a tool that allows you to test and troubleshoot IAM policies before applying them."},
              {q:"7. What is IAM Access Analyzer?",a:"Access Analyzer helps identify resources (like S3 buckets or IAM roles) that are shared publicly or across accounts."},
              {q:"8. What are service-linked roles?",a:"Service-linked roles are predefined roles linked directly to an AWS service, giving it permissions to manage resources on your behalf."},
              {q:"9. What is the difference between AWS-managed and customer-managed policies?",a:"AWS-managed: Created and maintained by AWS.Customer-managed: Created and customized by the user."},
              {q:"10. What are IAM credentials reports?",a:"A credentials report lists all IAM users and the status of their credentials (passwords, access keys, MFA, etc.)."},
              {q:"11. What is IAM access advisor?",a:"It shows which services a user or role has accessed and helps identify unused permissions."},
              {q:"12. Can IAM roles be assumed across AWS accounts?",a:"Yes — through cross-account roles, allowing access between different AWS accounts."},
              {q:"13. What is temporary security credential?",a:"Its a short-lived set of credentials generated via STS (Security Token Service), often used by IAM roles."},
              {q:"14. What is AWS STS (Security Token Service)?",a:"STS issues temporary credentials for users or applications to access AWS resources securely."},
              {q:"15. What is IAM best practice for AWS root user?",a:"Dont use it for daily tasks.Enable MFA.,Create admin IAM users instead.,Secure the root credentials."},
              {q:"16. What is resource-based trust policy?",a:"It defines who can access a specific AWS resource, like S3 bucket or Lambda function, directly from that resource."},
              {q:"17. What happens if an IAM policy has both “Allow” and “Deny”?",a:"Explicit Deny always overrides any Allow."},
              {q:"18. What is IAM JSON policy evaluation logic?",a:"AWS evaluates policies in this order:-Deny by default,Evaluate explicit “Allow”,Evaluate explicit “Deny” → takes precedence"},
              {q:"19. What is AWS Organizations, and how does it relate to IAM?",a:"AWS Organizations lets you manage multiple AWS accounts centrally.It works with IAM to apply service control policies (SCPs) across accounts."},
              {q:"20. What are IAM tagging and permissions boundaries?",a:"Tags: Add metadata (like department or project) to IAM users/roles.Permissions boundaries: Define maximum permissions an IAM entity can have.,Pro Tip for Freshers:-In interviews, focus on explaining key IAM concepts like:.Least privilege,Difference between user, role, and group,Policy structure,MFA and security best practices,Temporary credentials (STS)."}],

      LAMBDA:[{q:"1. What is AWS Lambda?",a:"AWS Lambda is a serverless compute service that lets you run code without managing servers. You only pay for the compute time your code uses."},
           {q:"2. What does “serverless” mean?",a:"“Serverless” means you don’t have to manage servers — AWS automatically handles provisioning, scaling, and maintenance."},
           {q:"3. What languages are supported by Lambda?",a:"Lambda supports:Python,Node.js,Java,C# (.NET Core),Go,Ruby,PowerShell,Custom runtimes (via container images)"},
           {q:"4. What is a Lambda function?",a:"A Lambda function is your code plus its configuration that runs in response to events (like an S3 upload or an API call)."},
           {q:"5. How do you trigger a Lambda function?",a:"You can trigger Lambda from:-S3 (object upload),API Gateway,SNS / SQS,CloudWatch Events,DynamoDB Streams,EventBridge, etc."},
           {q:"6. How do you create a Lambda function?",a:"Through:-AWS Management Console,AWS CLI,AWS SDKs,Infrastructure as Code (like CloudFormation or Terraform)"},
           {q:"7. What is the maximum execution time for a Lambda function?",a:"The maximum timeout for a Lambda function is 15 minutes (900 seconds)."},
           {q:"8. What is the default memory allocation in Lambda?",a:"AThe default is 128 MB, and it can be increased up to 10,240 MB (10 GB)."},
           {q:"9. What are the main components of AWS Lambda?",a:"Function code,Handler,Trigger (event source),Execution role (IAM),Environment variables"},
           {q:"10. What is an event in AWS Lambda?",a:"An event is data passed to a Lambda function to trigger it, like an S3 object upload or an API request."},
           {q:"11. What is the handler in Lambda?",a:"A handler is the entry point in your code where execution begins.Example: handler(event, context)"},
           {q:"12. What is the context object?",a:"t provides runtime information about the Lambda function (like request ID, timeout, and memory limit)."},
           {q:"13. How is Lambda priced?",a:"You pay for:Number of requests,Execution time (duration),Pricing is based on GB-seconds used."},
           {q:"14. What are Lambda Layers? ",a:" Layers are used to share common code, libraries, or dependencies across multiple Lambda functions. "},
           {q:" 15. What are Lambda environment variables? ",a:" Key-value pairs that store configuration data (like database URLs or API keys) accessible within the Lambda function. "},
           {q:" 16. What is AWS X-Ray in Lambda? ",a:" AWS X-Ray helps you trace and analyze requests to understand Lambda’s performance and identify bottlenecks or errors. "},
           {q:" 17. What are cold starts in Lambda? ",a:" A cold start occurs when Lambda initializes a new execution environment — it takes slightly longer than warm invocations. "},
           {q:" 18. What is a warm start in Lambda?",a:"A warm start happens when AWS reuses an existing execution environment — making the function run faster."},
           {q:" 19. Can Lambda functions access VPC resources? ",a:" Yes, Lambda can connect to a VPC by configuring VPC settings (subnets, security groups) in the function settings. "},
           {q:" 20. What are the key benefits of AWS Lambda? ",a:" No server management,Automatic scaling,Pay only for execution time,Easy integration with other AWS services,High availability and fault tolerance "},
          
           {q:" INTERMEDIATE LEVEL AWS LAMBDA INTERVIEW QUESTIONS ",a:" INTERMEDIATE LEVEL AWS LAMBDA INTERVIEW ANSWERS "},
          
           {q:" 1. What is the difference between EC2 and Lambda? ",a:" EC2: You manage servers, OS, scaling, and availability.Lambda: Fully managed and serverless — you just deploy code. "},
           {q:" 2. What is an event source mapping in Lambda? ",a:" It’s a configuration that connects Lambda to stream-based services (like DynamoDB Streams or SQS) to automatically trigger functions. "},
           {q:" 3. What is concurrency in AWS Lambda? ",a:" Concurrency is the number of function instances running at the same time. AWS automatically manages this based on requests. "},
           {q:" 4. What is reserved concurrency? ",a:" It guarantees a fixed number of concurrent executions for a specific function, ensuring availability. "},
           {q:" 5. What is provisioned concurrency? ",a:" It keeps a number of Lambda instances pre-initialized, reducing cold start latency for high-performance apps. "},
           {q:" 6. How does Lambda handle scaling? ",a:" Lambda automatically scales by running multiple instances of your function in response to the number of incoming events. "},
           {q:" 7. What are the deployment packages in Lambda? ",a:" A deployment package is a ZIP file or container image that includes your function code and dependencies. "},
           {q:" 8. What is the maximum size of a deployment package? ",a:" ZIP file (direct upload): 50 MB,ZIP from S3: 250 MB,Container image: Up to 10 GB "},
           {q:" 9. What is Lambda@Edge? ",a:" Lambda@Edge runs Lambda functions closer to users at AWS CloudFront edge locations — useful for low-latency content delivery. "},
           {q:" 10. What is the difference between synchronous and asynchronous Lambda invocation? ",a:" Synchronous: The caller waits for the result (e.g., API Gateway).Asynchronous: The event is queued, and Lambda runs in the background (e.g., S3, SNS) "},
           {q:" 11. What are Dead Letter Queues (DLQ) in Lambda? ",a:" DLQs (using SNS or SQS) store failed Lambda events for later debugging or reprocessing. "},
           {q:" 12. How can you secure your Lambda function? ",a:" Use IAM roles for permissions,Enable VPC access for private data,Use environment variable encryption (KMS),Apply least privilege principle "},
           {q:" 13. What is a Lambda destination? ",a:" estinations define what happens after a function’s success or failure — sending results to SNS, SQS, or EventBridge. "},
           {q:" 14. How do you monitor Lambda functions? ",a:" Using:-Amazon CloudWatch (metrics & logs),AWS X-Ray (tracing),AWS CloudTrail (API calls) "},
           {q:" 15. What is the AWS Lambda execution role? ",a:" It’s an IAM role that grants your function permission to access other AWS services (like S3, DynamoDB, etc.). "},
           {q:" 16. How does Lambda handle errors? ",a:" Automatically retries for asynchronous invocations,Logs errors in CloudWatch Logs,Supports DLQ and error handling destinations "},
           {q:" 17. What are Lambda container images? ",a:" Lambda can run functions packaged as container images (up to 10 GB), built with Docker. "},
           {q:" 18. What is the maximum payload size in AWS Lambda? ",a:" Synchronous: 6 MB,Asynchronous (event): 256 KB,Through API Gateway: 10 MB "},
           {q:" 19. What is Step Functions in AWS Lambda? ",a:" Step Functions coordinate multiple Lambda functions into workflows — managing sequence, retries, and state transitions. "},
           {q:" 20. How can you reduce Lambda cold start time? ",a:" Use Provisioned Concurrency,Keep package size small,Reuse connections outside the handler,Choose lighter runtimes (Node.js, Python)✅ Pro Tip for Freshers:When explaining Lambda in interviews:-Emphasize it’s event-driven and serverless,Highlight cost efficiency & automatic scaling,Be ready to explain a use case (like resizing an image when uploaded to S3) "},  ],

      ALB:[{q:"1. What is an Elastic Load Balancer (ELB)?",a:" ELB is a service that automatically distributes incoming traffic across multiple targets (like EC2 instances) to ensure high availability and reliability of applications. "},
            {q:" 2. Why do we use Load Balancers in AWS? ",a:" To distribute traffic evenly, avoid overload on a single server, and improve application performance and fault tolerance. "},
            {q:" 3. What are the types of Load Balancers in AWS? ",a:" Classic Load Balancer (CLB),Application Load Balancer (ALB),Network Load Balancer (NLB),Gateway Load Balancer (GWLB)"},
            {q:" 4. Which Load Balancer operates at Layer 7 of the OSI model? ",a:" The Application Load Balancer (ALB). "},
            {q:" 5. Which Load Balancer operates at Layer 4? ",a:" The Network Load Balancer (NLB). "},
            {q:" 6. What is a Target Group in ELB? ",a:" A target group is a collection of EC2 instances or IPs that receive traffic from a load balancer. "},
            {q:" 7. What is a Health Check in ELB? ",a:" A test performed by the ELB to check whether targets (EC2 instances) are healthy and ready to receive traffic. "},
            {q:" 8. What happens if a target fails a health check? ",a:" The ELB stops sending traffic to that target until it becomes healthy again. "},
            {q:" 9. Can a Load Balancer handle traffic across multiple Availability Zones? ",a:" Yes. ELB can distribute traffic across instances in multiple Availability Zones for high availability. "},
            {q:" 10. What are Listeners in ELB? ",a:" Listeners are processes that check for incoming connection requests using a specific protocol and port. "},
            {q:" 11. What is Cross-Zone Load Balancing? ",a:" It allows the ELB to evenly distribute traffic across all registered instances in all enabled Availability Zones. "},
            {q:" 12. What is Connection Draining (Deregistration Delay)? ",a:" It ensures that existing connections are completed before the instance is deregistered or terminated."},
            {q:" 13. Can ELB support HTTPS traffic? ",a:" Yes, by adding an SSL certificate to handle HTTPS requests. "},
            {q:" 14. What is Sticky Session (Session Affinity)? ",a:" AIt allows a user’s session to be consistently routed to the same target instance. "},
            {q:" 15. How does ELB improve fault tolerance? ",a:" By automatically routing traffic only to healthy instances across multiple AZs. "},
            {q:" 16. Can you attach security groups to an ELB? ",a:" Yes, for Application and Classic Load Balancers (not for NLBs). "},
            {q:" 17. What is the difference between CLB and ALB? ",a:" CLB works at Layer 4 and 7 (legacy), while ALB is modern and works purely at Layer 7 with advanced routing. "},
            {q:" 18. What are the supported protocols in ELB? ",a:" HTTP, HTTPS, TCP, UDP, and TLS."},
            {q:" 19. Can ELB integrate with Auto Scaling? ",a:" Yes, it automatically adds or removes instances as per scaling rules and health checks."},
            {q:" 20. What is the benefit of using ELB? ",a:" It ensures scalability, fault tolerance, and better performance for web applications."},
          
            {q:" Intermediate AWS ELB Interview Questions ",a:" Intermediate AWS ELB Interview Answer "},
          
            {q:" 1. What is the difference between Application Load Balancer (ALB) and Network Load Balancer (NLB)? ",a:" ALB handles HTTP/HTTPS (Layer 7) traffic with advanced routing; NLB handles TCP/UDP (Layer 4) for high performance and low latency. "},
            {q:" 2. What is Path-Based Routing in ALB? ",a:" It routes requests based on the URL path — for example, /images goes to one target group, /api to another."},
            {q:" 3. What is Host-Based Routing in ALB? ",a:" It routes traffic based on domain names — e.g., api.example.com to one target group, app.example.com to another. "},
            {q:" 4. What is a Listener Rule? ",a:" It defines how a load balancer routes traffic based on conditions like host headers or paths. "},
            {q:" 5. What is SSL Termination? ",a:" It’s when the load balancer decrypts HTTPS traffic before sending it to the target instances. "},
            {q:" 6. How can you monitor ELB performance? ",a:" Using Amazon CloudWatch metrics such as RequestCount, Latency, and HealthyHostCount. "},
            {q:" 7. What is the purpose of an idle timeout in ELB? ",a:" It determines how long a connection can remain idle before being closed. "},
            {q:" 8. How do you enable HTTPS in ALB? ",a:" By attaching an SSL certificate via AWS Certificate Manager (ACM) and setting up a listener on port 443. "},
            {q:" 9. Can ELB handle traffic for on-premises servers? ",a:" Yes, via IP-based target groups (Hybrid Architecture)."},
            {q:" 10. How can you restrict access to ELB? ",a:" By configuring Security Groups or AWS WAF (Web Application Firewall) with ALB."},
            {q:" 11. What is Deregistration Delay in ALB/NLB? ",a:" It’s the time an instance continues to serve existing connections before being removed from the target group. "},
            {q:" 12. What is Access Logging in ELB? ",a:" It records detailed logs about requests sent to your load balancer, stored in S3. "},
            {q:" 13. How does NLB achieve high performance? ",a:" By using static IPs and operating at Layer 4 for millions of requests per second. "},
            {q:" 14. What is the Gateway Load Balancer (GWLB)? ",a:" It allows you to deploy, scale, and manage third-party virtual appliances like firewalls. "},
            {q:" 15. Can we attach static IPs to a Load Balancer? ",a:" Yes, Network Load Balancers support Elastic IPs. "},
            {q:" 16. How does ELB integrate with Auto Scaling Groups? ",a:" The ELB automatically updates target groups as instances are added or removed by Auto Scaling. "},
            {q:" 17. What is Target Group Stickiness? ",a:" It ensures requests from the same client are routed to the same target for a specified duration. "},
            {q:" 18. How do you enable Cross-Zone Load Balancing? ",a:" It can be enabled in the ELB settings (on by default for ALB, optional for NLB). "},
            {q:" 19. What happens if all targets in a target group fail health checks? ",a:" The ELB returns a 503 Service Unavailable error to clients. "},
            {q:" 20. How does ELB contribute to application scalability? ",a:" It distributes traffic dynamically as new instances are launched, ensuring smooth scaling under varying load. "}, ],
      
        ROUTE53:[{q:"1. What is Amazon Route 53? ",a:"  Amazon Route 53 is a scalable and highly available Domain Name System (DNS) web service used to route users to applications on the internet. "},
                  {q:" 2. What does “53” stand for in Route 53? ",a:" The number 53 refers to the port number used by the DNS protocol (port 53). "},
                  {q:" 3. What are the main functions of Route 53? ",a:" Domain registration,DNS routing,Health checking and failover "},
                  {q:" 4. What is a Hosted Zone in Route 53? ",a:" A hosted zone is a container for records that define how traffic is routed for a domain or subdomain. "},
                  {q:" 5. What are the types of Hosted Zones? ",a:" Public Hosted Zone: For internet-accessible domains.Private Hosted Zone: For internal DNS resolution within a VPC. "},
                  {q:" 6. What is a DNS Record? ",a:" A DNS record is an entry in Route 53 that maps a domain name to an IP address or another resource. "},
                  {q:" 7. What are some common DNS record types in Route 53?",a:" A (IPv4 address),AAAA (IPv6 address),CNAME (Alias),MX (Mail Exchange),TXT (Text),NS (Name Server) "},
                  {q:" 8. What is an Alias Record in Route 53? ",a:" It’s a special record type used to map your domain name to AWS resources like ELB, CloudFront, or S3. "},
                  {q:" 9. What is TTL (Time to Live) in Route 53? ",a:" TTL defines how long DNS resolvers cache the record before requesting an update. "},
                  {q:" 10. Can Route 53 register domain names?",a:" Yes, Route 53 provides domain registration services for many TLDs (like .com, .org, .in, etc.). "},
                  {q:" 11. What is the difference between CNAME and Alias Record?",a:" CNAME maps one domain name to another, while Alias can map to AWS resources and supports root domains. "},
                  {q:" 12. What is a Health Check in Route 53? ",a:" It monitors the health of your endpoints and helps Route 53 route traffic only to healthy resources. "},
                  {q:" 13. How does Route 53 ensure high availability? ",a:" It automatically routes traffic to healthy resources and uses globally distributed DNS servers. "},
                  {q:" 14. Can Route 53 route traffic between AWS and non-AWS resources? ",a:" Yes, it can route traffic to any internet-accessible IP or domain name. "},
                  {q:" 15. What is Latency-Based Routing? ",a:" It routes traffic to the AWS region with the lowest network latency for the user. "},
                  {q:" 16. What is Weighted Routing? ",a:"It allows you to distribute traffic based on assigned weights to different resources."},
                  {q:" 17. What is Failover Routing? ",a:" It automatically redirects traffic to a backup resource when the primary resource becomes unhealthy. "},
                  {q:" 18. What is Geolocation Routing? ",a:" It routes traffic based on the user’s geographic location (like country or continent). "},
                  {q:" 19. Can Route 53 integrate with CloudFront?",a:" Yes, you can use Alias records to point your domain directly to a CloudFront distribution. "},
                  {q:" 20. What are NS Records in Route 53? ",a:" NS (Name Server) records identify the authoritative DNS servers for a domain. "},
                
                  {q:" Intermediate AWS Route 53 Interview Questions ",a:" Intermediate AWS Route 53 Interview Answers "},
                
                  {q:" 1. What is the difference between Latency-Based and Geolocation Routing? ",a:" Latency-Based: Routes based on response time (speed).Geolocation: Routes based on user’s physical location."},
                  {q:" 2. How does Route 53 achieve fault tolerance?",a:" By using health checks and failover routing policies to automatically switch to healthy endpoints. "},
                  {q:" 3. What is a DNS Failover?",a:" It’s the ability of Route 53 to detect unhealthy endpoints and route traffic to a backup automatically. "},
                  {q:" 4. What are the Routing Policies supported by Route 53? ",a:" Simple,Weighted,Latency-Based,Failover,Geolocation,Geoproximity,Multi-Value Answer"},
                  {q:" 5. What is Simple Routing Policy?",a:" It maps a domain name to a single resource (like one EC2 instance or ELB). "},
                  {q:" 6. What is Multi-Value Answer Routing?",a:" It returns multiple healthy IP addresses to DNS queries to help with load distribution."},
                  {q:" 7. What is Geoproximity Routing? ",a:" It routes traffic based on geographic proximity of users and can bias routing towards certain regions. "},
                  {q:" 8. Can you use Route 53 for internal DNS in a VPC? ",a:" Yes, by creating a Private Hosted Zone associated with your VPC. "},
                  {q:" 9. How does Route 53 Health Check work? ",a:" It sends periodic requests to endpoints (like HTTP or TCP) and marks them healthy or unhealthy based on response. "},
                  {q:" 10. Can Route 53 route traffic to multiple AWS regions? ",a:" Yes, using Latency-Based or Weighted routing across regions. "},
                  {q:" 11. How does Route 53 integrate with ELB (Elastic Load Balancer)? ",a:" You can create an Alias Record that points your domain directly to the ELB DNS name. "},
                  {q:" 12. Can Route 53 be used as a private DNS server? ",a:" Yes, by using Private Hosted Zones within Amazon VPC."},
                  {q:" 13. How does Route 53 handle DNS caching? ",a:" Resolvers cache DNS records for the duration of their TTL (Time to Live) value. "},
                  {q:" 14. What is the purpose of SOA (Start of Authority) record? ",a:" It provides information about the domain, such as the primary DNS server and refresh intervals. "},
                  {q:" 15. How can Route 53 be secured?",a:" By using IAM policies for DNS management and enabling DNSSEC (Domain Name System Security Extensions). "},
                  {q:" 16. What is DNSSEC in Route 53? ",a:" It adds cryptographic signatures to DNS data to prevent spoofing and attacks. "},
                  {q:" 17. How do you monitor Route 53 performance?",a:" Using Amazon CloudWatch metrics like Health Check Status and DNS Queries. "},
                  {q:" 18. Can Route 53 handle hybrid cloud routing? ",a:" Yes, it can route traffic between AWS resources and on-premises environments using IP-based targets. "},
                  {q:" 19. What are Route 53 Traffic Flow Policies? ",a:" Traffic Flow lets you visualize and manage complex routing configurations using a graphical console."},
                  {q:" 20. What happens if all endpoints in a routing policy fail health checks?",a:" Route 53 can be configured to return no response (fail closed) or route to a backup region if defined. "}],
        
        NLB:[{q:"1. What is a Load Balancer in AWS?",a:" A Load Balancer distributes incoming traffic across multiple targets (like EC2 instances) to ensure high availability and fault tolerance. "},
                  {q:" 2. What is Elastic Load Balancing (ELB)?",a:" Elastic Load Balancing (ELB) automatically distributes traffic across multiple targets, scaling with your application’s demand. "},
                  {q:" 3. What are the different types of Load Balancers in AWS? ",a:" Application Load Balancer (ALB),Network Load Balancer (NLB),Gateway Load Balancer (GLB),Classic Load Balancer (deprecated) "},
                  {q:" 4. What is an Application Load Balancer (ALB)?",a:" ALB operates at Layer 7 (HTTP/HTTPS) of the OSI model and routes requests based on content, such as URL path or hostname. "},
                  {q:" 5. What is a Network Load Balancer (NLB)?",a:" NLB operates at Layer 4 (TCP/UDP) and handles millions of requests per second with ultra-low latency. "},
                  {q:" 6. What is a Gateway Load Balancer (GLB)? ",a:" GLB is used to deploy and manage third-party virtual appliances (like firewalls or intrusion detection systems) at scale. "},
                  {q:" 7. What is a Classic Load Balancer (CLB)? ",a:" CLB is the legacy load balancer that operates at both Layer 4 and Layer 7, mainly for older EC2-Classic networks. "},
                  {q:" 8. What is the main difference between ALB and NLB?",a:" ALB: Works at Layer 7 (HTTP/HTTPS), supports advanced routing.NLB: Works at Layer 4 (TCP/UDP), designed for high-performance, low-latency workloads. "},
                  {q:" 9. What is a Target Group in AWS ELB? ",a:" A Target Group is a collection of EC2 instances or services that receive traffic from a load balancer. "},
                  {q:" 10. What is a Listener in AWS Load Balancer?",a:" A Listener checks for incoming requests on a specific port and protocol and forwards them to target groups. "},
                  {q:" 11. What are Health Checks in ELB? ",a:" Health checks are periodic tests used by the load balancer to determine if targets (instances) are healthy and available to receive traffic. "},
                  {q:" 12. What happens if a target fails a health check? ",a:" If a target fails health checks repeatedly, the load balancer stops sending traffic to that instance until it becomes healthy again. "},
                  {q:" 13. What protocols does ALB support?",a:" ALB supports HTTP and HTTPS protocols. "},
                  {q:" 14. What protocols does NLB support?",a:" NLB supports TCP, UDP, and TLS protocols. "},
                  {q:" 15. Can a Load Balancer handle SSL/TLS termination?",a:" Yes, ALB and NLB can handle SSL/TLS termination, offloading encryption and decryption from backend servers. "},
                  {q:" 16. What is SSL offloading? ",a:" It’s when the load balancer handles SSL encryption/decryption instead of backend servers, reducing their CPU load. "},
                  {q:" 17. Can a single Load Balancer route to multiple target groups?",a:" Yes, using listener rules, a Load Balancer can route requests to multiple target groups based on conditions like path or host. "},
                  {q:" 18. What is Cross-Zone Load Balancing? ",a:" Cross-Zone Load Balancing allows a load balancer to distribute traffic evenly across all instances in all Availability Zones. "},
                  {q:" 19. Is ELB highly available by default? ",a:" Yes, ELB automatically distributes traffic across multiple Availability Zones for fault tolerance. "},
                  {q:" 20. Can you use ELB with Auto Scaling? ",a:" Yes, ELB integrates seamlessly with Auto Scaling Groups (ASG) to automatically add or remove instances as demand changes. "},
                
                  {q:" Intermediate AWS Load Balancer Interview Questions ",a:" Intermediate AWS Load Balancer Interview Answers "},
                
                  {q:" 1. How does an Application Load Balancer perform routing?",a:" ALB uses listener rules that route traffic based on:Host-based routing (e.g., api.example.com),Path-based routing (e.g., /login, /user),Header or query string routing"},
                  {q:" 2. How does a Network Load Balancer perform routing?",a:" NLB routes traffic based on IP protocol data (Layer 4) and supports static IP addresses for predictable connections. "},
                  {q:" 3. How do you configure an HTTPS listener in ALB? ",a:" You need to:Create an HTTPS listener on port 443.,Attach an SSL certificate from AWS Certificate Manager (ACM)."},
                  {q:" 4. What is Sticky Session (Session Affinity) in ELB? ",a:" Sticky sessions ensure that a user’s requests are consistently routed to the same backend instance during a session."},
                  {q:" 5. How do you enable Sticky Sessions in ALB?",a:" In ALB, enable stickiness in the target group settings using an application cookie. "},
                  {q:" 6. What is the idle timeout in ELB? ",a:" It’s the duration a connection stays open without activity. For ALB, the default timeout is 60 seconds."},
                  {q:" 7. How do you log requests from a Load Balancer? ",a:" Enable Access Logs in ELB — they store detailed request information in an S3 bucket. "},
                  {q:" 8. What metrics can you monitor in CloudWatch for ELB? ",a:" RequestCount,HealthyHostCount,UnHealthyHostCount,Latency,HTTPCode_ELB_5XX_Count "},
                  {q:" 9. How does ALB integrate with ECS (Elastic Container Service)? ",a:" ALB routes traffic to containers in ECS using dynamic port mapping — it identifies which port each container listens on. "},
                  {q:" 10. How does NLB support static IPs? ",a:" Each subnet of an NLB gets a static IP address, or you can assign your own Elastic IPs (EIPs) for consistent addressing. "},
                  {q:" 11. What is the advantage of NLB over ALB for high-performance apps? ",a:" NLB can handle millions of requests per second with ultra-low latency, suitable for gaming, IoT, and real-time apps. "},
                  {q:" 12. Can ALB route traffic to Lambda functions? ",a:" Yes ✅ — ALB supports Lambda as a target, allowing it to trigger serverless backends directly. "},
                  {q:" 13. What is the purpose of the Target Group Health Check settings? ",a:" They determine how many failed checks mark an instance as unhealthy and how often to perform health checks. "},
                  {q:" 14. How does ELB handle SSL certificates?",a:" You can use AWS Certificate Manager (ACM) to manage and attach SSL/TLS certificates to your load balancer."},
                  {q:" 15. What is the benefit of using multiple listeners on a Load Balancer?",a:" It allows the same Load Balancer to handle different protocols or ports, e.g., HTTP:80 and HTTPS:443. "},
                  {q:" 16. What is the difference between public and internal load balancers? ",a:" Public (Internet-facing): Routes traffic from the internet.Internal: Routes traffic only within a VPC. "},
                  {q:" 17. How does Cross-Zone Load Balancing affect cost? ",a:" For ALB, it’s free. For NLB, cross-AZ data transfer charges apply. "},
                  {q:" 18. What is Deregistration Delay in Target Groups? ",a:" The Deregistration Delay controls how long ELB waits before stopping traffic to an instance marked for removal — default is 300 seconds. "},
                  {q:" 19. How can you ensure zero downtime during deployment using ELB? ",a:" Use:-Blue/Green deployment,Weighted target groups,Auto Scaling integration,to shift traffic gradually without downtime. "},
                  {q:" 20. How can you troubleshoot failed health checks? ",a:" Check:-The target’s security group rules,Health check path and port,Application response codes (200 OK expected),Instance logs or CloudWatch metrics "}, ],
     
      
    },
    devops: {
      GIT:[{q:"1. What is Git?",a:"Git is a distributed version control system that tracks changes in source code and allows multiple people to collaborate on projects efficiently."},
               {q:" 2. What is the difference between Git and GitHub? ",a:" Git: A version control tool. GitHub: A cloud-based hosting service for Git repositories. "},
               {q:" 3. What is a repository in Git? ",a:" A repository (repo) is a directory that contains all project files and the history of changes (commits)."},
               {q:" 4. What is a commit in Git? ",a:" A commit is a snapshot of your project’s changes at a particular point in time. "},
               {q:" 5. What command is used to create a new Git repository? ",a:" git init "},
               {q:" 6. How do you clone an existing repository? ",a:" git clone <repository_URL> "},
               {q:" 7. What command shows the current status of files in your repository?",a:" git status "},
               {q:" 8. How do you stage a file for commit? ",a:" git add <filename> "},
               {q:" 9. How do you commit the staged changes? ",a:" git commit -m `commit message` "},
               {q:" 10. How do you view the commit history? ",a:" git log "},
               {q:" 11. What is the purpose of .gitignore file? ",a:" It lists files and directories that Git should ignore (not track), such as temporary or build files. "},
               {q:" 12. How do you check the current branch in Git? ",a:" git branch"},
               {q:" 13. What is a branch in Git?",a:" A branch is a pointer to a specific commit — it allows you to work on new features independently. "},
               {q:" 14. How do you create a new branch?",a:" git branch <branch_name>"},
               {q:" 15. How do you switch to another branch?",a:" git checkout <branch_name> "},
               {q:" 16. How do you merge one branch into another? ",a:" Agit merge <branch_name> "},
               {q:" 17. What is the difference between git pull and git fetch? ",a:" git fetch downloads commits but doesn’t merge them.git pull downloads and merges automatically. "},
               {q:" 18. How do you delete a branch? ",a:" git branch -d <branch_name> "},
               {q:" 19. What is the command to view file differences before committing?",a:" git diff "},
               {q:" 20. What is the staging area in Git? ",a:" It’s a place where changes are stored temporarily before being committed to the repository. "},

               {q:" Intermediate Git Interview Questions ",a:" Intermediate Git Interview Answers "},

               {q:" 1. What is a remote repository in Git? ",a:" A remote repository is a version of your project hosted on a server (like GitHub, GitLab, or Bitbucket). "},
               {q:" 2. How do you add a remote repository? ",a:" git remote add origin <repository_URL> "},
               {q:" 3. What does git push do? ",a:" It uploads your local commits to a remote repository. "},
               {q:" 4. What does git pull do? ",a:" It fetches and merges changes from the remote repository into your current branch. "},
               {q:" 5. What is a merge conflict?",a:" A merge conflict occurs when changes in two branches affect the same lines of code differently. "},
               {q:" 6. How do you resolve a merge conflict? ",a:" Manually edit the conflicting files, remove conflict markers, and then commit the resolved changes. "},
               {q:" 7. What is the difference between git merge and git rebase? ",a:" Merge: Combines changes and preserves history.Rebase: Moves or re-applies commits on top of another base branch (creates a cleaner history). "},
               {q:" 8. How do you temporarily save changes without committing them?",a:" git stash "},
               {q:" 9. How do you apply stashed changes? ",a:" git stash apply "},
               {q:" 10. What is git revert used for?",a:" It creates a new commit that undoes the changes made by a previous commit. "},
               {q:" 11. What is git reset used for?",a:" It moves the current branch pointer to a previous commit, discarding or keeping changes depending on the mode. "},
               {q:" 12. Difference between git reset --hard and git reset --soft?",a:" --hard: Discards all local changes.,--soft: Keeps changes in the staging area."},
               {q:" 13. What is the purpose of git tag?",a:" Tags are used to mark specific commits, typically for version releases. "},
               {q:" 14. How do you see the list of all tags? ",a:" git tag "},
               {q:" 15. How do you delete a file from the repository? ",a:" git rm <filename>,git commit -m <Removed file> "},
               {q:" 16. What is a detached HEAD state in Git?",a:" It occurs when you checkout a specific commit instead of a branch, meaning new commits won’t belong to any branch."},
               {q:" 17. How can you see changes introduced by a specific commit?",a:" git show <commit_id> "},
               {q:" 18. How do you rename a branch?",a:" git branch -m <new_branch_name> "},
               {q:" 19. How can you undo the last commit but keep changes?",a:" git reset --soft HEAD~1 "},
               {q:" 20. What is Continuous Integration (CI) in relation to Git?",a:" It’s a DevOps practice where code pushed to Git is automatically built and tested using tools like Jenkins or GitHub Actions."}],

      GITHUB:[{q:"1. What is GitHub?",a:"GitHub is a cloud-based platform for hosting Git repositories, allowing multiple developers to collaborate, manage versions, and review code."},
              {q:" 2. How is GitHub different from Git? ",a:" Git is a version control system. GitHub is a cloud service that hosts Git repositories and provides collaboration features. "},
              {q:" 3. What is a repository in GitHub? ",a:" A repository (repo) is a storage space on GitHub that holds your project files, code, and commit history. "},
              {q:" 4. What is the difference between a public and private repository? ",a:" Public: Visible to everyone. Private: Only accessible to authorized users or team members. "},
              {q:" 5. How do you create a new repository on GitHub? ",a:" Go to GitHub → Repositories → New → Enter name → Choose visibility → Create repository. "},
              {q:" 6. What is a commit on GitHub? ",a:" A commit is a saved change or version of the project, with a unique ID and message describing what was changed. "},
              {q:" 7. What is a branch in GitHub? ",a:" A branch is a separate line of development that allows multiple developers to work on different features simultaneously. "},
              {q:" 8. What is the default branch in GitHub? ",a:" The default branch is usually named main (previously master). "},
              {q:" 9. What is a pull request (PR)? ",a:" A pull request is a request to merge changes from one branch into another, often used for code review before merging. "},
              {q:" 10. What is a fork in GitHub? ",a:" A fork is a copy of someone elses repository under your account, allowing you to modify it independently. "},
              {q:" 11. What is the difference between a clone and a fork? ",a:" Clone: Copies a repo from GitHub to your local system.Fork: Creates a copy in your GitHub account (for contributing to others’ projects). "},
              {q:" 12. How do you clone a repository from GitHub? ",a:" git clone <repository_URL> "},
              {q:" 13. What is GitHub Actions?",a:" GitHub Actions is a CI/CD automation tool that allows you to build, test, and deploy directly from your GitHub repository. "},
              {q:" 14. What is a README file? ",a:" A README.md file describes your project, its purpose, and how to use or install it."},
              {q:" 15. What is a GitHub Issue? ",a:" Issues are used to track bugs, enhancements, or tasks related to a repository. "},
              {q:" 16. What are GitHub Projects? ",a:" Projects are Kanban-style boards used for project management and task tracking within a repository. "},
              {q:" 17. How do you contribute to another user’s project on GitHub? ",a:" By forking their repository, making changes, and creating a pull request to propose your updates. "},
              {q:" 18. What is a GitHub Gist? ",a:" A Gist is a simple way to share small code snippets or notes publicly or privately. "},
              {q:" 19. How can you delete a repository in GitHub? ",a:" Go to Settings → Danger Zone → Delete this repository → Confirm. "},
              {q:" 20. What is the purpose of GitHub Discussions? ",a:" GitHub Discussions provide a forum for users to ask questions, share ideas, and collaborate outside of code changes. "},

              {q:" Intermediate GitHub Interview Questions ",a:" Intermediate GitHub Interview Answers "},

              {q:" 1. What is Continuous Integration (CI) in GitHub? ",a:" CI is a practice of automatically building and testing code whenever changes are pushed, ensuring integration issues are caught early. "},
              {q:" 2. How does GitHub Actions support CI/CD pipelines? ",a:" GitHub Actions allows you to create workflows using YAML files to automate builds, tests, and deployments. "},
              {q:" 3. Where do you define GitHub Action workflows? ",a:" In the .github/workflows/ directory inside your repository. "},
              {q:" 4. What is a workflow trigger in GitHub Actions? ",a:" It defines when a workflow should run, such as push, pull_request, or schedule.Example:on: push "},
              {q:" 5. What is a self-hosted runner in GitHub Actions? ",a:" A self-hosted runner is a custom machine that executes GitHub Actions workflows instead of GitHub’s default cloud runners. "},
              {q:" 6. How do you protect the main branch in GitHub? ",a:" By enabling branch protection rules under repository settings — such as requiring PR reviews before merging. "},
              {q:" 7. What ?is a merge conflict in GitHub? ",a:" It occurs when two commits change the same part of a file differently, requiring manual resolution."},
              {q:" 8. How do you resolve a merge conflict in GitHub? ",a:" You can resolve it manually in a local branch or directly using GitHub’s web editor, then commit the resolution. "},
              {q:" 9. What are GitHub Webhooks? ",a:" Webhooks allow GitHub to send real-time notifications to other systems (e.g., Jenkins, Slack) when certain events occur (like a push or PR). "},
              {q:" 10. What are GitHub Environments? ",a:" They define deployment environments (like dev, staging, production) for GitHub Actions workflows with specific rules or secrets. "},
              {q:" 11. What are GitHub Secrets? ",a:" Encrypted variables (like API keys or passwords) stored securely and used in workflows. "},
              {q:" 12. How can you automate code deployment from GitHub to AWS or other platforms?",a:" By using GitHub Actions or integrating GitHub with Jenkins, AWS CodePipeline, or Docker Hub."},
              {q:" 13. What is a GitHub Release? ",a:" Releases are versions of your project that include tagged commits and downloadable source code or binaries. "},
              {q:" 14. What is the purpose of a tag in GitHub? ",a:" Tags mark specific points in history (like v1.0) — often used for release versions."},
              {q:" 15. How do you collaborate using pull requests? ",a:" Developers create a PR, team members review the code, suggest changes, and merge it into the main branch after approval. "},
              {q:" 16. What is a code review in GitHub?",a:" It’s a process where team members review a pull request’s code before it’s merged, improving code quality and consistency. "},
              {q:" 17. How can you enforce review policies in GitHub? ",a:" By enabling branch protection rules — requiring approvals, passing checks, or no direct pushes to main."},
              {q:" 18. What is a GitHub organization? ",a:" An organization is a shared account for teams to manage multiple repositories and members under one workspace. "},
              {q:" 19. How can you manage permissions in GitHub? ",a:" By assigning roles (e.g., admin, maintainer, contributor, reader) within organizations or repositories. "},
              {q:" 20. What is GitHub Pages? ",a:" It’s a feature to host static websites directly from a GitHub repository — often used for documentation or portfolio pages. "}],

      ANSIBLE:[{q:"1. What is Ansible? ",a:"Ansible is an open-source IT automation tool used for configuration management, application deployment, orchestration, and provisioning in DevOps."},
                  {q:" 2. What are the main features of Ansible? ",a:" Agentless (no software required on target machines),Uses YAML for configurations,Idempotent (no repeated changes),Easy to learn and maintain"},
                  {q:" 3. Who developed Ansible?",a:" Ansible was developed by Michael DeHaan and later acquired by Red Hat."},
                  {q:" 4. What language is Ansible written in? ",a:" Ansible is written in Python."},
                  {q:" 5. What protocol does Ansible use to communicate with managed nodes? ",a:" Ansible uses SSH for Linux systems and WinRM for Windows systems."},
                  {q:" 6. What is an Inventory file in Ansible? ",a:" An inventory file is a list of target hosts or groups on which Ansible runs tasks.Default location: /etc/ansible/hosts"},
                  {q:" 7. What is an Ansible Playbook? ",a:" A playbook is a YAML file that defines one or more plays. Plays describe a set of tasks to be executed on hosts."},
                  {q:" 8. What is a Module in Ansible?",a:" Modules are small programs that perform specific tasks like installing software, copying files, or managing services.Examples: yum, copy, service, user."},
                  {q:" 9. What is a Task in Ansible? ",a:" A task is a single unit of action (e.g., install a package) that runs on the target system."},
                  {q:" 10. What is an Ad-Hoc Command in Ansible? ",a:" An Ad-Hoc command is a one-liner command used for quick operations without writing a playbook.Example:ansible all -m ping"},
                  {q:" 11. What is a Role in Ansible? ",a:" A role is a structured way to organize playbooks into reusable components (tasks, handlers, templates, variables, etc.)."},
                  {q:" 12. What is a Handler in Ansible? ",a:" Handlers are special tasks that run only when notified by another task (usually used to restart services after configuration changes)."},
                  {q:" 13. What is Idempotency in Ansible? ",a:" Idempotency ensures that running a playbook multiple times produces the same result — no redundant changes."},
                  {q:" 14. What is a Fact in Ansible? ",a:" Facts are system details (like IP, OS, memory) automatically collected from managed nodes at runtime."},
                  {q:" 15. How do you execute a playbook? ",a:" By using:-ansible-playbook playbook.yml"},
                  {q:" 16. What is YAML and why is it used in Ansible? ",a:" YAML (Yet Another Markup Language) is a human-readable data format used to define playbooks because it’s easy to write and understand."},
                  {q:" 17. What is Ansible Galaxy? ",a:" Ansible Galaxy is an online community for sharing and downloading Ansible roles and collections."},
                  {q:" 18. What is the default file extension of a playbook? ",a:" The default extension is .yml or .yaml."},
                  {q:" 19. Does Ansible require an agent to be installed on target systems?",a:" No, Ansible is agentless — it only needs SSH or WinRM access."},
                  {q:" 20. What is the command to check Ansible version? ",a:" ansible --version"},

                  {q:" Intermediate Ansible Interview Questions ",a:" Intermediate Ansible Interview Answers"},
                  
                  {q:" 1. Explain the architecture of Ansible. ",a:" Ansible has 3 main components:,Control Node – Machine where Ansible is installed.,Managed Nodes – Systems being automated.,Inventory – List of managed nodes."},
                  {q:" 2. What are Variables in Ansible? ",a:" Variables are used to store dynamic values that can be reused across playbooks.Example:-vars:  http_port: 80"},
                  {q:" 3. What are Templates in Ansible? ",a:" Templates (usually .j2 files using Jinja2) allow dynamic file generation based on variables.Example: generating nginx.conf with a variable port."},
                  {q:" 4. What is Ansible Tower (AWX)? ",a:" Ansible Tower (or its open-source version AWX) provides a web UI, REST API, role-based access control, and scheduling for managing Ansible automation."},
                  {q:" 5. What is a Dynamic Inventory? ",a:" A Dynamic Inventory automatically retrieves the list of hosts from external sources like AWS, Azure, or GCP instead of a static hosts file."},
                  {q:" 6. What is Ansible Vault used for? ",a:" Ansible Vault is used to encrypt sensitive data (like passwords or API keys) in playbooks or variable files."},
                  {q:" 7. How do you encrypt a file using Ansible Vault? ",a:" ansible-vault encrypt secrets.yml"},
                  {q:" 8. How do you decrypt a Vault file? ",a:" ansible-vault decrypt secrets.yml "},
                  {q:" 9. What is the use of the register keyword in Ansible?",a:" It stores the output of a command or task in a variable.Example:-command: uptime , register: result"},
                  {q:" 10. What are Loops in Ansible? ",a:" Loops allow repeating a task for multiple items.Example:- name: Install packages,yum:-name: <{{ item }}> ,state: present,loop:- ,- git-,    - nginx- ,   - docker"},
                  {q:" 11. What are Conditionals in Ansible? ",a:" Conditionals allow tasks to run only if certain conditions are true using when.Example:when: ansible_facts['os_family'] == <Debian>"},
                  {q:" 12. What is the purpose of “become” in Ansible? ",a:" become: yes allows privilege escalation (similar to sudo) to perform administrative tasks."},
                  {q:" 13. How do you test a playbook without applying changes? ",a:" Use check mode:ansible-playbook playbook.yml --check"},
                  {q:" 14. How do you limit playbook execution to specific hosts or groups?",a:" Use the --limit option:ansible-playbook playbook.yml --limit webservers"},
                  {q:" 15. How can you skip specific tags in Ansible? ",a:" ansible-playbook playbook.yml --skip-tags <install>"},
                  {q:" 16. What is a Callback Plugin in Ansible?",a:" Callback plugins control output formatting and can send logs or notifications to external systems (like Slack)."},
                  {q:" 17. How can you disable fact gathering in Ansible? ",a:" Add this in your playbook:gather_facts: no"},
                  {q:" 18. What are Roles used for in Ansible? ",a:" Roles allow playbooks to be modular and reusable by organizing tasks, variables, and templates into structured directories."},
                  {q:" 19. What is the difference between a Static and Dynamic Inventory? ",a:" Static: Defined manually in /etc/ansible/hosts.Dynamic: Generated automatically from cloud providers or APIs."},
                  {q:" 20. How do you handle errors in Ansible playbooks?",a:" Using keywords like ignore_errors: yes or error handling blocks (block, rescue, always)Example:- block:- name: Try task,command: /bin/false,rescue:- debug:,msg: <Error handled!>"}],

      MAVEN:[{q:"1. What is Maven?",a:"Maven is a build automation and project management tool used primarily for Java projects. It manages dependencies, builds, and project lifecycles."},
           {q:" 2. Who developed Maven? ",a:" Maven was developed by the Apache Software Foundation. "},
           {q:" 3. What is the main objective of Maven? ",a:" To simplify project build processes, dependency management, and project configuration using a standard structure. "},
           {q:" 4. What language is Maven written in? ",a:" Maven is written in Java."},
           {q:" 5. What is a POM file in Maven? ",a:" pom.xml (Project Object Model) is the core configuration file that defines a project’s build configuration, dependencies, plugins, and other settings."},
           {q:" 6. What is the default file name of Mavens configuration file?",a:" pom.xml "},
           {q:" 7. What does POM stand for? ",a:" POM stands for Project Object Model. "},
           {q:" 8. What is a Maven Repository? ",a:" A Maven Repository is a location where project artifacts (JARs, dependencies, plugins) are stored and retrieved during the build process. "},
           {q:" 9. What are the types of Maven repositories?",a:" Local Repository,Central Repository,Remote Repository "},
           {q:" 10. What is a Maven Dependency? ",a:" A dependency is an external JAR file or library that your project needs to compile or run."},
           {q:" 11. How do you specify dependencies in Maven? ",a:" Dependencies are defined in the pom.xml under the <dependencies> tag.Example:<dependency>  <groupId>org.springframework</groupId>  <artifactId>spring-core</artifactId>  <version>5.3.10</version></dependency> "},
           {q:" 12. What is the default location of the local Maven repository?",a:" ~/.m2/repository (in the user’s home directory). "},
           {q:" 13. What is the command to build a Maven project? ",a:" mvn clean install "},
           {q:" 14. What is the purpose of the mvn clean command? ",a:" It deletes the target directory (which contains previous build outputs) to ensure a fresh build. "},
           {q:" 15. What is the purpose of the mvn compile command? ",a:" It compiles the source code of the project. "},
           {q:" 16. What is the purpose of the mvn test command? ",a:" It runs all test cases defined in the project using testing frameworks like JUnit or TestNG."},
           {q:" 17. What is the purpose of the mvn package command? ",a:" It packages the compiled code into a JAR or WAR file as specified in the POM."},
           {q:" 18. What is the purpose of the mvn install command? ",a:" It installs the packaged JAR/WAR file into the local repository for use in other local projects. "},
           {q:" 19. What is the purpose of the mvn deploy command? ",a:" It copies the final packaged artifact to a remote repository for sharing with other developers."},
           {q:" 20. What is the lifecycle in Maven? ",a:" A lifecycle defines a sequence of phases in the build process.The main lifecycles are:,default (build & deploy),clean (clean artifacts),site (generate documentation)"},
          
           {q:" Intermediate Maven Interview Questions ",a:" Intermediate Maven Interview Answers "},
          
           {q:" 1. What are the phases in the default Maven lifecycle? ",a:" validate -> compile -> test -> package -> verify -> install -> deploy "},
           {q:" 2. What is a Maven plugin? ",a:" Plugins are used to extend Maven’s functionality and perform tasks like compiling, testing, packaging, or deploying projects. "},
           {q:" 3. What is the purpose of the maven-compiler-plugin? ",a:" It compiles the project’s source code.,Example:<plugin> <groupId>org.apache.maven.plugins</groupId><artifactId>maven-compiler-plugin</artifactId><version>3.8.1</version><configuration><source>1.8</source><target>1.8</target></configuration></plugin>"},
           {q:" 4. What are Maven Coordinates? ",a:" Each artifact in Maven is uniquely identified by:groupId,artifactId,version,packaging "},
           {q:" 5. What is the difference between install and deploy in Maven? ",a:" install: Copies artifact to the local repository.deploy: Copies artifact to a remote repository for team use."},
           {q:" 6. What is the purpose of the settings.xml file? ",a:" settings.xml configures user-specific settings like repository locations, credentials, or proxy details.Default location:- ~/.m2/settings.xml "},
           {q:" 7. How can you skip tests while building in Maven? ",a:" Use the -DskipTests flag:mvn package -DskipTests "},
           {q:" 8. What is the difference between clean install and clean package? ",a:" clean package: Builds and packages the project.clean install: Packages the project and installs it in the local repository. "},
           {q:" 9. What is the Super POM? ",a:" The Super POM is Maven’s default POM that all projects inherit from. It defines default settings like repositories and plugin versions. "},
           {q:" 10. What is an Archetype in Maven? ",a:" An archetype is a project template that helps create new Maven projects with predefined structure and settings.Command:mvn archetype:generate "},
           {q:" 11. What is the purpose of mvn dependency:tree?",a:" It displays all project dependencies in a hierarchical tree structure, helping identify conflicts or duplicates."},
           {q:" 12. How does Maven handle transitive dependencies? ",a:" If dependency A requires dependency B, Maven automatically downloads B as a transitive dependency. "},
           {q:" 13. What is the scope element in a Maven dependency? ",a:" It defines where a dependency is available.Types:compile,provided,runtime,test,system,import "},
           {q:" 14. What is the difference between compile and provided scope?",a:" compile: Required at compile and runtime.provided: Available at compile time but not included in the final package (e.g., servlet APIs in web servers). "},
           {q:" 15. How can you update all dependencies in Maven? ",a:" Use:-mvn versions:use-latest-versions "},
           {q:" 16. What is the difference between SNAPSHOT and RELEASE versions in Maven? ",a:" SNAPSHOT: Ongoing development version (not final).RELEASE: Stable, production-ready version. "},
           {q:" 17. What is a parent POM in Maven? ",a:" A parent POM allows sharing configurations (like dependencies or plugins) among multiple child projects. "},
           {q:" 18. What is a multi-module project in Maven? ",a:" A project with a parent POM and multiple submodules (child projects) managed together. "},
           {q:" 19. What is the purpose of mvn site command? ",a:" It generates project documentation (like reports, dependency graphs) in the target/site directory. "},
           {q:" 20. How can you analyze project dependency conflicts in Maven? ",a:" Use:-mvn dependency:analyze,It reports unused or missing dependencies and helps clean up the pom.xml. "}],
          
      JENKINS:[{q:"1. What is Jenkins?",a:"Jenkins is an open-source automation server used to automate building, testing, and deploying applications as part of a CI/CD pipeline."},
            {q:" 2. Who developed Jenkins? ",a:" Jenkins was originally developed by Kohsuke Kawaguchi as Hudson and later renamed to Jenkins. "},
           {q:" 3. What language is Jenkins written in? ",a:" Jenkins is written in Java. "},
           {q:" 4. What is the purpose of Jenkins in DevOps? ",a:" Jenkins automates the software development lifecycle (SDLC) — including build, test, and deployment — to enable Continuous Integration (CI) and Continuous Deployment (CD). "},
           {q:" 5. What is Continuous Integration (CI)? ",a:" CI is the practice of merging all developers’ code into a shared repository frequently and automatically building and testing it. "},
           {q:" 6. What is Continuous Deployment (CD)? ",a:" CD is the process of automatically deploying every change that passes automated tests to production."},
           {q:" 7. What are Jenkins Pipelines? ",a:" A pipeline is a series of steps defined in a Jenkinsfile that automates the process of building, testing, and deploying code. "},
           {q:" 8. What is a Jenkinsfile? ",a:" A Jenkinsfile is a text file that defines a Jenkins pipeline, written using Groovy syntax. "},
           {q:" 9. What are the two types of Jenkins pipelines?",a:" Declarative Pipeline,Scripted Pipeline"},
           {q:" 10. What is the default port number of Jenkins? ",a:" By default, Jenkins runs on port 8080. "},
           {q:" 11. What is a Jenkins job?",a:" A job is a task or project Jenkins runs — such as building code, running tests, or deploying applications."},
           {q:" 12. How can Jenkins be installed? ",a:" As a WAR file (java -jar jenkins.war),Using package managers (apt, yum),Docker container,Cloud-based services like AWS, Azure, or Kubernetes."},
           {q:" 13. What are Jenkins plugins? ",a:" Plugins extend Jenkins’s functionality (e.g., Git, Maven, Docker, Slack). Jenkins has over 1,800 plugins available. "},
           {q:" 14. What is the Jenkins dashboard? ",a:" The dashboard is the main user interface where you can view jobs, builds, and manage Jenkins configurations. "},
           {q:" 15. What is a build trigger in Jenkins?",a:" A build trigger defines how and when Jenkins should start a job. Examples:On code commit (GitHub webhook),On schedule (CRON),Manually "},
           {q:" 16. How can you trigger a Jenkins job automatically? ",a:" By using webhooks, SCM polling, or scheduled CRON jobs. "},
           {q:" 17. What is a freestyle project in Jenkins? ",a:" A freestyle project is the simplest type of Jenkins job used to build, test, or deploy software manually or automatically. "},
           {q:" 18. What is the use of the “Post-build actions” in Jenkins? ",a:" Post-build actions define what Jenkins should do after a build completes, like sending emails, archiving artifacts, or deploying. "},
           {q:" 19. How can you check the build history in Jenkins?",a:" From the Build History section on the Jenkins dashboard for each job. "},
           {q:" 20. What is the difference between Jenkins and other CI tools (like GitLab CI or CircleCI)? ",a:" Jenkins is open-source, plugin-rich, and self-hosted, while others may be cloud-native and more limited in customization. "},
          
           {q:" Intermediate Jenkins Interview Questions ",a:" Intermediate Jenkins Interview Answers "},
          
           {q:" 1. What are Jenkins nodes and masters? ",a:" Master (Controller): Manages the Jenkins environment and schedules jobs.,Node (Agent/Slave): Executes jobs assigned by the master."},
           {q:" 2. What is a Jenkins agent? ",a:" An agent is a remote machine connected to the Jenkins master that executes build jobs."},
           {q:" 3. How can Jenkins be integrated with version control systems (VCS)? ",a:" Using plugins like:Git Plugin (for Git/GitHub),SVN Plugin,Bitbucket Plugin "},
           {q:" 4. What is SCM polling in Jenkins? ",a:" SCM (Source Code Management) polling checks the repository for changes at regular intervals and triggers builds if new commits are found. "},
           {q:" 5. What is the difference between polling and webhooks? ",a:" Polling: Jenkins checks for changes periodically.,Webhook: The VCS notifies Jenkins immediately when a change occurs (faster and more efficient). "},
           {q:" 6. What is a parameterized build in Jenkins? ",a:" A build that accepts user-defined input parameters (e.g., branch name, environment) before starting. "},
           {q:" 7. How can you secure Jenkins? ",a:" Enable authentication and authorization.,Use role-based access control (RBAC).,Integrate with LDAP or Active Directory.,Always use HTTPS. "},
           {q:" 8. What is Blue Ocean in Jenkins? ",a:" Blue Ocean is a modern Jenkins UI that provides a visual pipeline editor and improved visualization for builds."},
           {q:" 9. What are artifacts in Jenkins? ",a:" Artifacts are output files generated by a build (like .jar, .war, .zip) that Jenkins can store and share. "},
           {q:" 10. How can you archive artifacts in Jenkins? ",a:" Use the “Archive the artifacts” post-build action or define it in a Jenkinsfile:-archiveArtifacts 'target/*.jar' "},
           {q:" 11. What is the purpose of the “Pipeline as Code” concept? ",a:" It allows storing pipeline definitions (Jenkinsfiles) inside version control repositories — improving traceability and automation. "},
           {q:" 12. What is the syntax for a simple declarative pipeline? ",a:" pipeline {  agent any  stages {    stage('Build') {  steps {  echo 'Building...'      }  }stage('Test') { steps { echo 'Testing...'  }  }  },}"},
           {q:" 13. How can Jenkins be integrated with Docker?",a:" Use the Docker Plugin to build images.,Define Docker agents in pipelines.Example:agent {  docker { image 'maven:3.8.1' }} "},
           {q:" 14. How can Jenkins be integrated with Maven? ",a:" By using the Maven Plugin to run builds:mvn clean install,or through Jenkinsfile steps:sh 'mvn package'"},
           {q:" 15. How can Jenkins be integrated with Ansible? ",a:" You can call Ansible playbooks in a Jenkins pipeline using:,sh 'ansible-playbook deploy.yml',or through the Ansible Plugin. "},
           {q:" 16. How do you back up Jenkins configurations? ",a:" By backing up:$JENKINS_HOME directory,Jobs, plugins, and user configurations,Or by using plugins like ThinBackup."},
           {q:" 17. How can Jenkins notify developers about build results? ",a:" Email notifications,Slack notifications (via Slack Plugin),Webhook callbacks "},
           {q:" 18. How do you schedule a build in Jenkins? ",a:" Using CRON syntax under “Build periodically”:,Example: H/15 * * * * → triggers every 15 minutes."},
           {q:" 19. What is a shared library in Jenkins? ",a:" Shared libraries allow teams to reuse common pipeline code across multiple Jenkinsfiles. "},
           {q:" 20. What are common issues you might face in Jenkins pipelines?",a:" Plugin compatibility errors,Misconfigured agents,SCM credential issues,Build failures due to dependency errors,Timeout or permission issues "}],      

      DOCKER:[{q:"1. What is Docker?",a:"Docker is an open-source platform used to build, ship, and run applications inside containers, ensuring consistent environments across development and production."},
              {q:" 2. What is a Docker Container? ",a:" A container is a lightweight, portable unit that contains everything an application needs to run — including code, runtime, libraries, and dependencies. "},
             {q:" 3. What is the difference between a VM (Virtual Machine) and a Docker container? ",a:" Feature	Virtual Machine	Docker Container,OS	Runs full OS	Shares host OS kernel,Size	Heavy (GBs)	Lightweight (MBs),Boot time	Minutes	Seconds,Isolation	Hardware-level	Process-level "},
             {q:" 4. What is Docker Engine? ",a:" Docker Engine is the core component that runs and manages containers on a host system. "},
             {q:" 5. What is a Docker Image? ",a:" A Docker Image is a read-only template that contains the instructions to create a container (like a blueprint). "},
             {q:" 6. How do you create a Docker image?",a:" By writing a Dockerfile and running:-,docker build -t myimage . "},
             {q:" 7. What is a Dockerfile? ",a:" A Dockerfile is a text file containing commands and instructions to build a Docker image. "},
             {q:" 8. What is Docker Hub? ",a:" Docker Hub is a cloud-based registry where you can store and share Docker images publicly or privately. "},
             {q:" 9. How do you download an image from Docker Hub? ",a:" Use the command:,docker pull <image-name> "},
             {q:" 10. How do you run a Docker container?",a:" Use:-docker run <image-name> "},
             {q:" 11. How can you list running containers? ",a:" docker ps "},
             {q:" 12. How can you stop a running container?",a:" docker stop <container_id>"},
             {q:" 13. How can you remove a container? ",a:" docker rm <container_id> "},
             {q:" 14. How can you remove an image? ",a:" docker rmi <image_id> "},
             {q:" 15. What is the purpose of the docker-compose tool? ",a:" docker-compose allows you to define and manage multi-container applications using a YAML file. "},
             {q:" 16. What is the default network driver in Docker? ",a:" The default driver is bridge. "},
             {q:" 17. How can you view Docker images on your system? ",a:" docker images "},
             {q:" 18. What is a Docker Volume? ",a:" A volume is used for persistent data storage in containers — data stored in volumes remains even if containers are removed. "},
             {q:" 19. What is docker exec used for? ",a:" docker exec allows you to run a command inside a running container, e.g.:-,docker exec -it <container_id> bash "},
             {q:" 20. Can multiple containers share the same image? ",a:" Yes ✅, multiple containers can be created from the same image and run independently."},

             {q:" Intermediate Docker Interview Questions ",a:" Intermediate Docker Interview Answers "},

             {q:" 1. What are the main components of Docker architecture? ",a:" Docker Client (CLI commands)Docker Daemon (runs containersDocker Images,Docker Containers,Docker Registry (Hub) "},
             {q:" 2. What is the purpose of Docker Daemon (dockerd)? ",a:" dockerd is the background service that manages images, containers, networks, and volumes. "},
             {q:" 3. What is a multi-stage Docker build? ",a:" It’s a technique to optimize image size by using multiple FROM statements — only the final build stage’s artifacts are included. "},
             {q:" 4. How do you expose a port from a container? ",a:" By using:-Dockerfile:,EXPOSE 8080,Or command line:,docker run -p 8080:80 nginx "},
             {q:" 5. How can you check logs of a container? ",a:" docker logs <container_id> "},
             {q:" 6. How do you inspect a Docker container? ",a:" docker inspect <container_id>This provides detailed JSON output of configuration and status. "},
             {q:" 7. What is the difference between docker run and docker start? ",a:" docker run creates and starts a new container.,docker start starts an existing stopped container. "},
             {q:" 8. What is the purpose of .dockerignore file? ",a:" It excludes files and directories (like .git, node_modules) from being copied into the Docker image during build. "},
             {q:" 9. How can you link two containers for communication? ",a:" Use Docker networks or compose to connect containers within the same network. "},
             {q:" 10. What are Docker namespaces and cgroups? ",a:" They are Linux kernel features that Docker uses for:-Namespaces: Isolation (process, network, mount),cgroups: Resource control (CPU, memory limits) "},
             {q:" 11. What is the difference between ENTRYPOINT and CMD in Dockerfile? ",a:" Directive	Purpose,ENTRYPOINT	Defines the main executable,CMD	Provides default arguments to ENTRYPOINT,Example:,ENTRYPOINT <python, app.py>,CMD <--debug>] "},
             {q:" 12. How can you make a container restart automatically? ",a:" Use the --restart flag:,docker run --restart=always myapp"},
             {q:" 13. What is the purpose of the docker-compose.yml file? ",a:" It defines services, networks, and volumes for multi-container applications.Example version ,  3 services   web -,image: nginx,ports:  -  80:80 "},
             {q:" 14. What are Docker Networks used for? ",a:" Docker networks enable communication between containers.,Types include:,bridge,host,overlay,none"},
             {q:" 15. What is an Overlay Network in Docker? ",a:" An overlay network allows containers on different Docker hosts to communicate — typically used in Docker Swarm. "},
             {q:" 16. What is Docker Swarm? ",a:" Docker Swarm is Docker’s native container orchestration tool for managing a cluster of Docker nodes. "},
             {q:" 17. How can you check the resource usage of containers? ",a:" docker stats "},
             {q:" 18. What is the difference between Docker and Kubernetes?",a:" Feature	Docker	Kubernetes,Purpose	Containerization	Orchestration,Scope	Runs single containers	Manages multiple containers,Scaling	Manual	Automatic "},
             {q:" 19. How can you remove all stopped containers at once? ",a:" docker container prune"},
             {q:" 20. What are the best practices for writing a Dockerfile?",a:" Use small base images (e.g., alpine),Combine RUN commands to reduce layers,Use .dockerignore,Pin image versions,Keep containers stateless"}],

      KUBERNETES:[{q:"1. What is Kubernetes?",a:"Kubernetes (K8s) is an open-source container orchestration platform developed by Google to automate deployment, scaling, and management of containerized applications."},
        {q:" 2. What problem does Kubernetes solve? ",a:" It automates container management tasks like deployment, scaling, load balancing, and self-healing, which are difficult to manage manually at scale. "},
           {q:" 3. What is a Node in Kubernetes? ",a:" A Node is a worker machine (physical or virtual) that runs pods and is managed by the master node. "},
           {q:" 4. What is a Pod? ",a:" A Pod is the smallest deployable unit in Kubernetes — it contains one or more containers that share storage, network, and specifications."},
           {q:" 5. What is a Cluster in Kubernetes? ",a:" A Cluster is a group of nodes (worker + master) that run containerized applications managed by Kubernetes. "},
           {q:" 6. What is a Master Node (Control Plane)? ",a:" The Master Node controls and manages the Kubernetes cluster. It runs key components like:,API Server,Scheduler,Controller Manager,etcd (key-value store) "},
           {q:" 7. What is etcd in Kubernetes? ",a:" etcd is a distributed key-value store used by Kubernetes to store cluster data, such as configuration and state information. "},
           {q:" 8. What is kubectl? ",a:" kubectl is the command-line tool used to communicate with the Kubernetes cluster (API Server)."},
           {q:" 9. What is a Deployment in Kubernetes? ",a:" A Deployment is a higher-level abstraction that manages ReplicaSets and ensures that a specified number of pods are always running."},
           {q:" 10. What is a ReplicaSet? ",a:" A ReplicaSet ensures a defined number of pod replicas are running at any given time. "},
           {q:" 11. What is a Namespace? ",a:" Namespaces are used to divide cluster resources among multiple users or teams — useful for large environments. "},
           {q:" 12. What is a Service in Kubernetes? ",a:" A Service provides a stable IP and DNS name to access a set of Pods, even if Pods change. "},
           {q:" 13. What are the types of Kubernetes Services? ",a:" ClusterIP – Internal access only,NodePort – External access via a specific port,LoadBalancer – External access through a cloud load balancer,ExternalName – Maps to external services (DNS)"},
           {q:" 14. What is a ConfigMap?",a:" A ConfigMap stores non-confidential configuration data in key-value pairs, used by Pods."},
           {q:" 15. What is a Secret in Kubernetes?",a:" A Secret stores sensitive information like passwords or API keys, in base64-encoded format. "},
           {q:" 16. What is the difference between ConfigMap and Secret? ",a:" Feature	ConfigMap	Secret,Data type	Non-sensitive	Sensitive,Encoding	Plain text	Base64 encoded "},
           {q:" 17. What is a Label in Kubernetes? ",a:" Labels are key-value pairs attached to objects (like Pods) for identification, organization, and selection. "},
           {q:" 18. What is a Selector in Kubernetes? ",a:" Selectors are used to filter Kubernetes objects based on labels. "},
           {q:" 19. What is the role of the Scheduler in Kubernetes? ",a:" The Scheduler decides which node a pod should run on based on resource requirements and constraints."},
           {q:" 20. What is Minikube? ",a:" Minikube is a lightweight Kubernetes implementation used to run Kubernetes locally for learning and testing."},

           {q:" Intermediate Kubernetes Interview Questions",a:" Intermediate Kubernetes Interview Answers"},

           {q:" 1. What is the difference between a Pod and a Deployment? ",a:" A Pod runs containers directly.,A Deployment manages Pods and ensures desired state (e.g., scaling, updates)."},
           {q:" 2. What is a DaemonSet? ",a:" A DaemonSet ensures that a copy of a Pod runs on every node in the cluster (used for log collection, monitoring agents, etc.). "},
           {q:" 3. What is a StatefulSet? ",a:" A StatefulSet is used for stateful applications like databases. It provides stable network IDs and persistent storage. "},
           {q:" 4. What is a Job in Kubernetes? ",a:" A Job runs a batch process and ensures it completes successfully. "},
           {q:" 5. What is a CronJob? ",a:" A CronJob is used to schedule Jobs to run periodically (like cron tasks in Linux). "},
           {q:" 6. What is Ingress in Kubernetes?",a:" Ingress manages external access (HTTP/HTTPS) to services in the cluster — it provides routing, SSL termination, and domain mapping."},
           {q:" 7. What is a NodePort Service? ",a:" A NodePort service exposes a Pod to the outside world on a specific port of every node in the cluster."},
           {q:" 8. What is a LoadBalancer Service? ",a:" It integrates with cloud provider load balancers to route external traffic to your application. "},
           {q:" 9. What is a Kubernetes Volume?",a:" A Volume provides persistent storage that lives beyond the lifecycle of a Pod. "},
           {q:" 10. What is the difference between Persistent Volume (PV) and Persistent Volume Claim (PVC)? ",a:" Term	Description,PV	Storage resource in the cluster,PVC	Request for storage by a user "},
           {q:" 11. What is a Taint and Toleration?",a:" They are used to control which pods can be scheduled on certain nodes.,Taint: Marks a node to repel pods.,Toleration: Allows a pod to be scheduled on a tainted node. "},
           {q:" 12. What is Node Affinity? ",a:" Node Affinity ensures pods are scheduled on specific nodes based on labels."},
           {q:" 13. How can you perform rolling updates in Kubernetes? ",a:" By using Deployments — update the image version and apply:kubectl apply -f deployment.yaml,Kubernetes automatically updates pods one by one. "},
           {q:" 14. How can you roll back a Deployment? ",a:" kubectl rollout undo deployment/<deployment-name> "},
           {q:" 15. How do you view the status of Pods? ",a:" kubectl get pods "},
           {q:" 16. How do you check the logs of a Pod? ",a:" kubectl logs <pod-name> "},
           {q:" 17. How do you get detailed information about a Pod? ",a:" kubectl describe pod <pod-name> "},
           {q:" 18. How do you scale a Deployment? ",a:" kubectl scale deployment <deployment-name> --replicas=5 "},
           {q:" 19. What is Helm in Kubernetes? ",a:" Helm is a package manager for Kubernetes, used to install, upgrade, and manage applications (called charts). "},
           {q:" 20. What is the difference between Kubernetes and Docker Swarm? ",a:" Feature	Kubernetes	Docker Swarm,Scalability	Highly scalable	Less scalable,Auto-healing	Yes	Limited,Networking	Complex	Simple,Load balancing	Advanced (Ingress)	Basic "}]
    }
  };
  
  let currentSet=[], currentIndex=0;
  
  function openSection(category, service){
    document.getElementById("main-page").classList.add("hidden");
    document.getElementById("qa-page").classList.remove("hidden");
    currentSet = qaData[category][service];
    currentIndex=0;
    document.getElementById("section-title").textContent = service + " Q&A";
    showQA();
  }
  
  function showQA(){
    const questionEl = document.getElementById("question");
    const answerEl = document.getElementById("answer");
    const counterEl = document.getElementById("counter");
    if(currentIndex < currentSet.length){
      questionEl.textContent = currentSet[currentIndex].q;
      answerEl.textContent = currentSet[currentIndex].a;
      counterEl.textContent = `Question ${currentIndex+1} of ${currentSet.length}`;
    } else {
      questionEl.textContent = "🎉 Hurray! Well done!";
      answerEl.textContent = "Click 'Main Menu' to return.";
      counterEl.textContent = '';
    }
  }
  
  function nextQuestion(){ currentIndex++; showQA(); }
  function prevQuestion(){ if(currentIndex>0) currentIndex--; showQA(); }
  function goHome(){
    document.getElementById("qa-page").classList.add("hidden");
    document.getElementById("main-page").classList.remove("hidden");
  }
  